# Required variables to be defined in build definition and their default values:
#  - imageBuilder.pathArgs: <empty>
#  - imageBuilder.queueArgs: <empty>
#  - publishRepoPrefix: public/
#  - sourceBuildId: $(Build.BuildId)
#  - stages: build;test;publish
#  - waitForIngestionEnabled: true

trigger: main
pr: none

variables:
- template: templates/variables/common.yml

stages:
- template: ../common/templates/stages/build-test-publish-repo.yml
